version: '3'
services:
  feed-tool:
    build: .
    ports:
      - "127.0.0.1:8081:8080"
    restart: always

  nuget-dl:
    build: .
    # 不直接對外，僅在docker network內部可見
    expose:
      - "8080"
    environment:
      - PORT=8080
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - feed-tool
      - nuget-dl
    restart: always