version: '3'
networks:
  web:
    external: true
    name: traefik_web

services:
  nuget-dl:
    build: .
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nuget-dl.rule=Host(`[your-domain]`)"
      - "traefik.http.routers.nuget-dl.entrypoints=web"
      - "traefik.http.services.nuget-dl.loadbalancer.server.port=8080"
    networks:
      - web
    restart: always